version: '3.8'

services:
  web:
    image: docker/getting-started
    ports:
      - "80:80"
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
