services:
  b4_ros2:
    container_name: b4_ros2
    image: b4_ros2:latest
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER_NAME=${USER_NAME:-ros}
        - GROUP_NAME=${GROUP_NAME:-ros}
    environment:
      - DISPLAY=host.docker.internal:0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-1}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-1}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - ./src:/home/${USER_NAME:-ros}/ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "6080:6080"
    tty: true
    stdin_open: true
    working_dir: /home/${USER_NAME:-ros}/ws
